// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrW3oAIdHjwUmHULYETc0D849zY1GDxgk',
    appId: '1:170167402709:web:2a82de6205d3576473e25c',
    messagingSenderId: '170167402709',
    projectId: 'fir-cb505',
    authDomain: 'fir-cb505.firebaseapp.com',
    storageBucket: 'fir-cb505.firebasestorage.app',
    measurementId: 'G-Z0VD0ZB216',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxZEw9hpiOBGbMFAYQmy55o9W-PAThilk',
    appId: '1:170167402709:android:0d1c8ef90a65b6ae73e25c',
    messagingSenderId: '170167402709',
    projectId: 'fir-cb505',
    storageBucket: 'fir-cb505.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0oTy247GjwbVS7G4pXcpXeXCinwlNWCg',
    appId: '1:170167402709:ios:e6565bbf8088bfea73e25c',
    messagingSenderId: '170167402709',
    projectId: 'fir-cb505',
    storageBucket: 'fir-cb505.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0oTy247GjwbVS7G4pXcpXeXCinwlNWCg',
    appId: '1:170167402709:ios:e6565bbf8088bfea73e25c',
    messagingSenderId: '170167402709',
    projectId: 'fir-cb505',
    storageBucket: 'fir-cb505.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrW3oAIdHjwUmHULYETc0D849zY1GDxgk',
    appId: '1:170167402709:web:4502b33537b5967373e25c',
    messagingSenderId: '170167402709',
    projectId: 'fir-cb505',
    authDomain: 'fir-cb505.firebaseapp.com',
    storageBucket: 'fir-cb505.firebasestorage.app',
    measurementId: 'G-YG8ZW3N27G',
  );
}
